import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { FrontPage } from "./components/frontPage";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      {
          user.isSignedIn ? 
          <>
            <FrontPage />                      
            <button className="bg-white rounded-full p-1 shadow-md shadow-black w-28 text-xl font-bold font-serif mt-60"><SignOutButton/></button>
          </> 
          : 
          <>
            <h1 className="text-white text-5xl font-bold font-serif">Welcome to Recruitment Service</h1>          
            <button className="bg-white rounded-full p-1 shadow-md shadow-black w-28 text-xl font-bold font-serif mt-60"><SignInButton /></button>
          </>
        }     
      </main> 
    </>
  );
}