import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const instructors = api.instructor.get.useQuery();
  const user = useUser();
  return (
    <>
      <Head>
        <title>Next-T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {
          user.isSignedIn ? 
          <>
            <h1 className="text-white">Welcom to T3 Stack Project</h1>
            <ul>
              {instructors.data?.map(instructor => {
                  return (
                    <li key={instructor.id} className="text-white">
                      {instructor.name}
                    </li>
                  );
              })}
              </ul>
            <button className="bg-white"><SignOutButton/></button>
          </> 
          : 
          <>
            <h1 className="text-white">Hello</h1>          
            <button className="bg-white"><SignInButton /></button>
          </>
        }       
      </main>
    </>
  );
}
